import { Employee } from "./types";

export const employees: Employee[] = [
  {
    firstName: "Rivaldo",
    lastName: "Lima",
    gender: "male",
    position: "Chefe de turno",
    permission: "manager",
    email: "rivaldo.lima@ecoiberia.com",
    password: "123456",
    age: { dateOfBirth: "1985-08-14" },
    shift: 1,
    locker: 21,
    absences: [{ date: "2025-08-20", type: "justified" }],
    tardiness: [
      {
        date: "2025-09-02",
        type: "unjustified",
        checkInTime: "08:30",
        hourOfTardiness: 0.5,
      },
    ],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-10",
    },
    epi: {
      items: ["Luvas", "Óculos de proteção", "Protetor auricular"],
      receivedAt: "2025-05-10",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-04-01",
      endDate: "2025-04-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 3,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/rivaldo-lima.pdf",
    },
  },
  {
    firstName: "Ricardo",
    lastName: "Madureira",
    gender: "male",
    position: "Chefe de triagem",
    permission: "manager",
    email: "ricardo.madureira@ecoiberia.com",
    password: "123456",
    age: { dateOfBirth: "1988-02-10" },
    shift: 2,
    locker: 32,
    absences: [],
    tardiness: [],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-10",
    },
    epi: {
      items: ["Luvas", "Máscara"],
      receivedAt: "2025-05-10",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-05-01",
      endDate: "2025-05-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 3,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/ricardo-madureira.pdf",
    },
  },
  {
    firstName: "Anderson",
    lastName: "Carvalho",
    gender: "male",
    position: "Triador(a)",
    permission: "owner",
    email: "anderson.carvalho@ecoiberia.com",
    password: "123456",
    age: { dateOfBirth: "1993-06-10" },
    shift: 3,
    locker: 64,
    absences: [{ date: "2025-09-21", type: "unjustified" }],
    tardiness: [
      {
        date: "2025-09-15",
        type: "justified",
        checkInTime: "08:12",
        hourOfTardiness: 0.2,
      },
    ],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-12",
    },
    epi: {
      items: ["Luvas", "Óculos de proteção"],
      receivedAt: "2025-05-12",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-06-01",
      endDate: "2025-06-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 2,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/anderson-carvalho.pdf",
    },
  },
  {
    firstName: "Yasmim",
    lastName: "Freitas Carvalho",
    gender: "female",
    position: "Triador(a)",
    permission: "manager",
    email: "y.freitascarvalho@gmail.com",
    password: "123456",
    age: { dateOfBirth: "1993-03-24" },
    shift: 3,
    locker: 65,
    absences: [
      { date: "2025-09-10", type: "justified" },
      { date: "2025-09-21", type: "unjustified" },
    ],
    tardiness: [
      {
        date: "2025-09-15",
        type: "justified",
        checkInTime: "08:12",
        hourOfTardiness: 0.2,
      },
    ],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-12",
    },
    epi: {
      items: ["Luvas", "Óculos de proteção"],
      receivedAt: "2025-05-12",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-06-01",
      endDate: "2025-06-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 2,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/yasmim-freitas.pdf",
    },
  },
  {
    firstName: "Erick",
    lastName: "Vicente",
    gender: "male",
    position: "Abre fardos",
    permission: "user",
    email: "erick.vicente@ecoiberia.com",
    password: "123456",
    age: { dateOfBirth: "1997-11-02" },
    shift: 1,
    locker: 17,
    absences: [],
    tardiness: [],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-10",
    },
    epi: {
      items: ["Luvas", "Protetor auricular"],
      receivedAt: "2025-05-10",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-08-01",
      endDate: "2025-08-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 3,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/erick-vicente.pdf",
    },
  },
  {
    firstName: "Joel",
    lastName: "Silva",
    gender: "male",
    position: "Lavagem",
    permission: "user",
    email: "joel.silva@ecoiberia.com",
    password: "123456",
    age: { dateOfBirth: "1990-12-17" },
    shift: 2,
    locker: 28,
    absences: [{ date: "2025-09-05", type: "justified" }],
    tardiness: [],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-11",
    },
    epi: {
      items: ["Luvas", "Protetor auricular"],
      receivedAt: "2025-05-11",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-07-01",
      endDate: "2025-07-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 2,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/joel-silva.pdf",
    },
  },
  {
    firstName: "Solange",
    lastName: "Silva",
    gender: "female",
    position: "Triador(a)",
    permission: "user",
    email: "solange.silva@ecoiberia.com",
    password: "123456",
    age: { dateOfBirth: "1992-05-09" },
    shift: 2,
    locker: 31,
    absences: [],
    tardiness: [],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-12",
    },
    epi: {
      items: ["Luvas", "Máscara"],
      receivedAt: "2025-05-12",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-06-01",
      endDate: "2025-06-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 2,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/solange-silva.pdf",
    },
  },
  {
    firstName: "Wagner",
    lastName: "Silva",
    gender: "male",
    position: "Abre fardos",
    permission: "user",
    email: "wagner.silva@ecoiberia.com",
    password: "123456",
    age: { dateOfBirth: "1995-01-20" },
    shift: 3,
    locker: 42,
    absences: [],
    tardiness: [],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-13",
    },
    epi: {
      items: ["Luvas", "Protetor auricular"],
      receivedAt: "2025-05-13",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-07-01",
      endDate: "2025-07-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 3,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/wagner-silva.pdf",
    },
  },
  {
    firstName: "Aline",
    lastName: "Moreira",
    gender: "female",
    position: "Triador(a)",
    permission: "user",
    email: "aline.moreira@ecoiberia.com",
    password: "123456",
    age: { dateOfBirth: "1994-10-05" },
    shift: 1,
    locker: 15,
    absences: [],
    tardiness: [],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-12",
    },
    epi: {
      items: ["Luvas", "Máscara"],
      receivedAt: "2025-05-12",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-09-01",
      endDate: "2025-09-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 2,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/aline-moreira.pdf",
    },
  },
  {
    firstName: "Anup",
    lastName: "Mohamed",
    gender: "male",
    position: "Triador(a)",
    permission: "user",
    email: "anup.mohamed@ecoiberia.com",
    password: "123456",
    age: { dateOfBirth: "1991-03-10" },
    shift: 2,
    locker: 23,
    absences: [],
    tardiness: [],
    uniform: {
      items: ["Calça", "Camisa Polo", "Botas"],
      receivedAt: "2025-05-12",
    },
    epi: {
      items: ["Luvas", "Óculos de proteção"],
      receivedAt: "2025-05-12",
    },
    contract: {
      type: "Tempo integral",
      startDate: "2024-07-01",
      endDate: "2025-07-01",
      monthsDuration: 12,
      daysDuration: 365,
      renewalInMonths: 3,
      contractorCompany: "ecoiberia",
      pdfFile: "/contracts/anup-mohamed.pdf",
    },
  },
];
